public class Main {
    public static void main(String[] args) {
        System.out.println(Thread.currentThread().getName());
        MyThread t = new MyThread();
        System.out.println(t.getName());//name generated by jvm
        Thread.currentThread().setName("Ojesh's Thread");
        System.out.println(Thread.currentThread().getName());
        System.out.println(10/0);
        

    }
}

class MyThread extends Thread{
    @Override
    public void run(){
        System.out.println("Child Thread");
    }
}